### ISSUE TITLE
option for xkcd alt text?

### ISSUE THREAD

**Issue by Hisfantor** [geirawsm/swaylockcomics#3]
would it be possible to make the xkcd alt text optional?

**Comment by geirawsm** [comment]
I'm sure this will be possible. I'm putting it on the todo-list.

**Comment by geirawsm** [comment]
Added a new function in 1d22b57babf915224354a19b93687d839af0c2b3.
@Hisfantor could you try the new version and test it?

**Comment by Hisfantor** [comment]
works great, thank you. Awesome project, keep it up :)

**Comment by geirawsm** [comment]
Thanks! :D
